name: Build & Deploy to instance

on:
  push:
    branches:
      - main      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

    - name: Deploy to AWS Lightsail
      env:
        SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        SSH_USER: ${{ secrets.LIGHTSAIL_SSH_USER }}
        SSH_HOST: ${{ secrets.LIGHTSAIL_SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
        cd /home/${{ secrets.LIGHTSAIL_SSH_USER }}/app
        # Stop and remove the old container if it exists
        sudo docker stop servicio-container || true
        sudo docker rm servicio-container || true
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        sudo docker run -d --name servicio-container -p 80:80 --restart unless-stopped ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        EOF